

--------------------------------------------------------------- MAGNITUDE ------------------------------------------------------------
-- Find the Total Number of Customers by Countries
SELECT
	country,
	COUNT(customer_key) AS Total_Customers
FROM [gold.customers]
GROUP BY country
ORDER BY Total_Customers DESC

-- Find the Total Customers by Gender
SELECT 
	gender AS Gender,
	COUNT(customer_key) AS Total_Customers
FROM [gold.customers]
GROUP BY gender
ORDER BY Total_Customers DESC

-- What is the average cost in each category?
SELECT 
	category AS Category,
	AVG(cost) AS Average_Cost
FROM [gold.products]
GROUP BY category
ORDER BY Average_Cost DESC

-- What is the total Revenue generated by each category?
SELECT 
	P.category AS Category,
	SUM(F.sales_amount) AS Total_Revenue
FROM [gold.fact_sales] f
LEFT JOIN [gold.products] p
ON p.product_key = f.product_key
GROUP BY category
ORDER BY Total_Revenue DESC


-- Find the total revenue generated by each customer
SELECT
	c.customer_number  Customer_ID,
	c.first_name First_Name,
	c.last_name Last_Name,
SUM(f.sales_amount) AS Total_Revenue 
FROM [gold.fact_sales] f
LEFT JOIN [gold.customers] c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_number,
	c.first_name,
	c.last_name
ORDER BY Total_Revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
	c.country AS Country,
	SUM(f.quantity) AS Sold_Items
FROM [gold.fact_sales] f
LEFT JOIN [gold.customers] c
ON c.customer_key= f.customer_key
GROUP BY c.country
ORDER BY Sold_Items DESC

-- What Product Line Generated the most revenue

SELECT 
	p.category AS Category,
	p.subcategory AS Subcategory,
	p.product_line Product_Line,
SUM(f.sales_amount) AS Top_Revenue_Line
FROM [gold.fact_sales] f
LEFT JOIN [gold.products] p
ON p.product_key = f.product_key
GROUP BY 
	p.category,
	p.subcategory,
	p.product_line
ORDER BY Top_Revenue_Line DESC